### ISSUE TITLE
client is incorrectly named

### ISSUE THREAD

**Issue by ob7** [BitcoinInterestOfficial/BitcoinInterest#12]
Whether you build from source or download the linux version, the client is called bitcoin-qt but should properly be called bitcoin-interest-qt or something that distinguishes it from original bitcoin client.

If my system has both bitcoin-qt and bitcoin interest in my path there will be a naming conflict.

**Comment by mathis1337** [comment]
this is not an issue, more a personal opinion. closing. If you need help, right click, then select rename and you may call it whatever you wish.

**Comment by ob7** [comment]
Well I have an automated build system, so renaming it after compilation is not really an option.  
So for me this is an issue because my system won't be able to have both bitcoin and bitcoin-interest installed at the same time.  
Why should it be called bitcoin-qt when it is actually bitcoin-interest-qt???

**Comment by ob7** [comment]
Unless you know of a way to override the name of the output during compilation ... otherwise I'd have to fork this just to run it alongside normal bitcoin.

**Comment by mathis1337** [comment]
after compilation for make install you can rename the shared libraries to avoid naming conflict. We can add this to our list of many things with progpow switch to do, however, exchanges and many others have not had any issues, so its not a high priority. Thank you.
