### ISSUE TITLE
install message should be changed (currently only 2GB needed not 150GB)

### ISSUE THREAD

**Issue by ob7** [BitcoinInterestOfficial/BitcoinInterest#13]
Not a high priority of course especially since you guys are focused on ProgPoW switch, but whenever there is free time I would suggest changing the message on the wallet when you first install on windows.  The wallet tells us we need over 150GB of disk space to install the wallet, but I believe that message is just left over from the original bitcoin wallet because the current wallet only takes up a little under 2GB of disk space for the chaindata.

I actually uninstalled all my games in order to install bitcoin-interest because I thought the message was accurate. RIP!

**Comment by mathis1337** [comment]
This is a good recommendation, we will do this. Thank you! Though the blockchain does grow, so we might rather put a range. 👍
