### ISSUE TITLE
Was ProgPoW a bad idea for BI?

### ISSUE THREAD

**Issue by lookfirst** [BitcoinInterestOfficial/BitcoinInterest#16]
**

**Comment by mathis1337** [comment]
No issue, just an opinion. Closing. Also Ethereum will be going PoS.

**Comment by lookfirst** [comment]
If [ProgPoW happens](https://cointelegraph.com/news/eth-dev-suggests-moving-to-asic-friendly-algorithm-after-progpow-decision), it will happen before PoS (if that happens as well). Even when there is Ethereum PoS, it will take X amount of time before it fully replaces PoW. They will run in parallel for an indeterminate amount of time.

Let this closed issue be referenced when BI is under 51% attack.

Cheers
