### ISSUE TITLE
Replay protection?

### ISSUE THREAD

**Issue by isle2983** [BitcoinInterestOfficial/BitcoinInterest#3]
In `src/script/interpreter.h`, `FORKID_BCI` is declared as `79`, which is then incorporated in signature hash.

Bitcoin Gold does the same declaration of `FORKID_BTG` as `79` and follows the same process.

I believe this means that transactions between the BTG and BCI chain are replayable against eachother.

**Comment by mathis1337** [comment]
The incorrect ID was committed due to typing error. New numbers have been added and will be established in V2 release shortly. 

Thank you.

**Comment by leto** [comment]
FYI this replay protection is still broken:

https://github.com/BitcoinInterestOfficial/BitcoinInterest/blob/master/src/script/interpreter.h#L35
