### ISSUE TITLE
why testnet is down

### ISSUE THREAD

**Issue by mabbas1975** [BitcoinInterestOfficial/BitcoinInterest#8]
Hello
we develop an application based on BCI but the testnet is down, should i add a specific node for testnet?

**Comment by mathis1337** [comment]
Hello, testnet is down as we are live. If a project is good we will provide BCI for testing on mainnet. Please come on to telegram and message @mathis1337 please.

**Comment by mabbas1975** [comment]
Hello, we make a new pool and we want to make sure that everything is good when finding blocks
